---
title: "Kaikkien aikojen EM-futisveikkaus 2024"
output: html_document
---

Kilpailu koostuu alkulohkojen otteluiden tulosten ja lohkosijoitusten veikkaamisesta ja pudotuspelipuun muodostamisesta (ns. [bracket](https://fi.wikipedia.org/wiki/Jalkapallon_Euroopan-mestaruuskilpailut_2024#Pudotuspelit) sekä palkittavien pelaajien valinnoista. Kaikki valinnat tehdään viimeistään ennen turnauksen ensimmäistä ottelua.

## Tulosveikkaus

Tulosveikkaus jokaiseen alkulohkon otteluun. Oikeasta veikkauksista palkintaa kerrointa vastaavalla pistemäärällä.

Kilpailussa käytettävät lopulliset kertoimet päivitetään mahdollisimman lähellä turnauksen alkua, joten kertoimet saattavat poiketa hieman alustavista kertoimista. Kertoimia ei päivitetä enää turnauksen alettua.

Pisteytys:

  1. __Täysin oikea tulos__ - 2 $\times$ kerrointa vastaava määrä pisteitä
  2. __Oikea vakiomerkki (1X2)__ - kerrointa vastaava määrä pisteitä

Esimerkki [talven 2022 MM-kisojen vastaavasta tulosveikkauksesta](https://joniok.github.io/mmveikkaus2022/).

## Alkulohkojen sijoitukset 

Veikataan jokaisen joukkueen lopullista sijoitusta alkulohkossa. Samaa sijoitusta ei voi veikata useammalle joukkueelle samassa lohkossa.

__2 pistettä jokaisesta oikein sijoitetusta joukkueesta__


## Pudotuspelipuu

Jokainen pelaaja muodostaa oman pudotuspelipuunsa, jonka perusteella veikataan jokaisesta pudotuspelivaiheesta eteneviä joukkueita. Pisteitä saa myös oikeasta valinnasta, vaikka joukkue etenisi eri kohdasta pudotuspelipuuta kuin mihin joukkueen oli itse sijoittanut.

| Vaihe             	| Pisteet 	| Veikattavien joukkueiden lkm 	|
|-------------------	|----------	|------------------------------	|
| Neljännesvälierät 	| 4        	| 8 joukkuetta                 	|
| Puolivälierät     	| 8        	| 4 joukkuetta                 	|
| Välierät          	| 12       	| 2 joukkuetta                 	|
| Finaali           	| 16       	| 1 joukkue                    	|

## Palkinnot

### Henkilövalinnat

| Palkinto                                   	| Selite                                     	| Pisteet    	|
|--------------------------------------------	|--------------------------------------------	|------------	|
| Player of the Tournament                   	| _Paras pelaaja_                            	| 15         	|
| Top goalscorer                             	| _Paras maalintekijä_ [^1]                  	| 15         	|
| Young Player of the Tournament             	| _Paras korkeintaan 22-vuotias pelaaja_[^2] 	| 10         	|
| Finaalin tuomari                           	|                                            	| 10         	|
| Man of the Match Award                     	| _Eniten Man of the Match-valintoja_        	| 5          	|
| Team of the Tournament _(11 player squad)_ 	| _UEFA:n turnauksen paras joukkue_          	| 33 (11x3p) 	|

[^1]: Jos useammalla pelaajalla on sama maalimäärä, jaetaan kultainen kenkä pelaajalle, jolla on pelaajista eniten syöttöjä. Jos tilanne on edelleen tasan, valitaan vähemmän minuutteja pelannut pelaaja voittajaksi. Ks. [tie breaker-säännöt](https://en.wikipedia.org/wiki/UEFA_European_Championship_awards#Top_goalscorer).
[^2]: Syntynyt 1.1.2002 tai myöhemmin.

## Yhteenveto

Alla yhteenveto eri osuuksissa saatavista pisteistä.

| Osuus                    	| Max. pisteet                     	|
|--------------------------	|----------------------------------	|
| Tulosveikkaus            	| 2 $\times$ kertoimien summa[^3]. 	|
| Alkulohkojen sijoitukset 	| 64                               	|
| Pudotuspelipuu           	| 114                              	|
| Pelaajavalinnat          	| 98                               	|


[^3]: Tarkentuu lopullisten kertoimien mukaan.
